main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: Publications
    url: /publications/
    weight: 30
  - name: Tools
    url: /tools/
    weight: 40
  - name: Database
    url: /database/
    weight: 50
