main:
  - name: About
    url: /
    weight: 10
  - name: Research
    url: /research/
    weight: 20
  - name: Publications
    url: /publications/
    weight: 30
  - name: Tools
    url: /tools/
    weight: 40
  - name: Novel Magnets
    url: /database/
    parent: Tools
    weight: 1
  - name: FINDMAGSYM
    url: https://findmagsym.streamlit.app/
    parent: Tools
    weight: 2
  - name: MAGIRREP
    url: /tools/magirrep.html
    parent: Tools
    weight: 3
